services:
  nginx:
    image: nginx:alpine
    container_name: crud_nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - appnet

  db:
    image: mariadb:latest
    container_name: crud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: crud_phpmyadmin
    restart: always
    ports:
      - ${PMA_EXPOSE_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:

